### ISSUE TITLE
[BUG] 对share对象的一部分进行 useAtom 访问时,出现意外行为

### ISSUE THREAD

**Issue by FairyScript** [heluxjs/helux#116]
Sandbox: https://codesandbox.io/p/sandbox/helux-issue-5llqw7?file=%2Fsrc%2FApp.tsx%3A23%2C1

问题描述: 

```tsx
const [state, setState] = share(() => ({
  a: {
    count: 1,
  },
}));

<Child a={state.a} />

const Child: React.FC<{ a: { count: number } }> = ({ a }) => {
  const [snap] = useAtom(a); // snap 指向 state, 而不是 state.a

//...

}

```

对 `share` 对象的属性进行 `useAtom`时, 返回的state对象指向最顶层的 `state` 而不是 `state.a`. 但使用`$(a.count)`访问则能正常响应.

期望行为: `useAtom(a)` 可以正确返回 `state.a` 的只读形式

---

btw, 面对类似的子组件需要atom的一部分,但是并不希望父组件响应该值.且子组件无法直接从根访问的情况下,最佳实践是什么?

**Comment by fantasticsoul** [comment]
你这个用法目前没有给你报错（后续会补齐这个逻辑，useAtom  only accept root shared state），按道理来说是不允许只传一部分给useAtom的，useAtom 总是传入根 atom，然后用户在外部自己读取部分值，读到什么依赖就是什么，比如你希望传递`state.a` 则是
```ts
const [ state ] = useAtom(rootState);
<Child a={state.a} />
```

如果你不希望父组件响应，就不要在父组件里使用`useAtom`，而子组件里使用，尽可能的靠近数据消费的地方使用`useAtom`，而不是透传，因为使用了`useAtom`的组件就会感知数据变化，读取`state`值会收窄依赖，不读的话就是根值依赖

或者试试`signal`，直接绑定到视图的渲染位置：
https://heluxjs.github.io/helux/guide/signal

**Comment by FairyScript** [comment]
明白了,感谢
