### ISSUE TITLE
[question] stopArrDep 具体行为

### ISSUE THREAD

**Issue by FairyScript** [heluxjs/helux#156]
CodeSandbox: https://codesandbox.io/p/sandbox/helux-arr-tz6wlx?file=%2Fsrc%2FApp.tsx%3A13%2C24

根据文档,我对 `stopArrDep` 的理解是依赖收集会追踪数据中**对象内属性**的修改,形如
```js
for (const item of draft) {
  item.age += 1; // 数组内对象引用不变,内部属性变更
}
```

在本示例中,我通过三种方式进行了atom的修改:

- 使用 `for-of` 修改数据内元素
- 使用 `for-in` 获取index, 并直接替换数组元素 (例子中并未对对象进行深拷贝,但不影响结果)
- 使用 index 直接修改

在例子中无论 `stopArrDep` 如何设置, 方式 1 都无法更新视图, 方式 2 和 3 都可以正常更新.是否是我对该参数的行为理解有误? helux 是否支持上述方式1形式的修改?

**Comment by fantasticsoul** [comment]
我通过你的演示链接发现 for of 不更新的问题了，我要排查一下看看具体的深层原因

**Comment by fantasticsoul** [comment]
`4.2.7`已修复，[limu支持代理数组迭代器](https://github.com/tnfe/limu/commit/bbfc5102e801b13aa1b3bb241214c5fa9ef5fd82)
