### ISSUE TITLE
share 通过ctx调用setState  操作数组新增删除操作数组数据依赖收集无效

### ISSUE THREAD

**Issue by HECHONG999** [heluxjs/helux#160]
问题描述：
那如果使用 defindActions 定义状态对应的修改函数去改能正常更新，但我直接使用 sharex 的ctx.setState 去设置就不行。

复现地址：
https://codesandbox.io/p/github/HECHONG999/helux-share/main?file=%2Fsrc%2FApp.js%3A18%2C28&workspaceId=b5ac2349-b955-4963-8cf8-c0476e7082a7

**Comment by fantasticsoul** [comment]
链接打不失败，请确认下呢

**Comment by HECHONG999** [comment]
抱歉忘记公开了 

https://codesandbox.io/p/github/HECHONG999/helux-share/main?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltvk0e5100063b6mtbhury3q%2522%252C%2522sizes%2522%253A%255B70.9657594381036%252C29.034240561896397%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltvk0e5100023b6m01o6f8lb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltvk0e5100043b6m91t2z3py%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltvk0e5100053b6mbl6wgs6u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B54.275554917031826%252C45.724445082968174%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltvk0e5100023b6m01o6f8lb%2522%253A%257B%2522id%2522%253A%2522cltvk0e5100023b6m01o6f8lb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltwm5vkq00023b6khv094rfp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltwm5vkq00023b6khv094rfp%2522%257D%252C%2522cltvk0e5100053b6mbl6wgs6u%2522%253A%257B%2522id%2522%253A%2522cltvk0e5100053b6mbl6wgs6u%2522%252C%2522activeTabId%2522%253A%2522cltvk5u7901qj3b6mvocgvaia%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cltvk5u7901qj3b6mvocgvaia%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cltvk0e5100043b6m91t2z3py%2522%253A%257B%2522id%2522%253A%2522cltvk0e5100043b6m91t2z3py%2522%252C%2522activeTabId%2522%253A%2522cltwm8hvn003i3b6mkq6lq9hx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltvk0e5100033b6m8whagxcx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltvk3v430017difygxmu1ix9%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Fjavascript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522cltvk2eh7009t3b6mxoql5rv9%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522cltvk5pws01lr3b6m9j1l48u1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522GIT_LOG%2522%252C%2522shellId%2522%253A%2522cltwm8fsp001vdify2zzc6e5q%2522%252C%2522id%2522%253A%2522cltwm8hvn003i3b6mkq6lq9hx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by fantasticsoul** [comment]
非block区域，需要使用`useState`获取到的状态才有依赖收集功能
错误写法
![image](https://github.com/heluxjs/helux/assets/7334950/6a8d7391-cb3a-4220-bd6c-44e2757d2188)

正确写法
![image](https://github.com/heluxjs/helux/assets/7334950/ccf0ff59-24f6-40a4-8a50-cbee2d19af36)
