### ISSUE TITLE
error only-dev-mode tip: moduleName AuthWithModule@Loading duplicate!

### ISSUE THREAD

**Issue by chong-intrii** [heluxjs/helux#163]
nextjs 热加载模式下提示Error 
<img width="1837" alt="image" src="https://github.com/heluxjs/helux/assets/146180085/d07db8c7-54e7-4c62-ba9d-2f76647a3c94">

**Comment by fantasticsoul** [comment]
更新到`4.3.5`即可，针对 loading 不再做提示
