### ISSUE TITLE
[bug] 报错Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by zogwosh** [heluxjs/helux#166]
[复现地址:](https://codesandbox.io/s/floral-forest-gv9t89?file=/App.tsx)

**Comment by fantasticsoul** [comment]
禁止闭包里使用数据参与逻辑计算，因为代理对象会被回收，目前可以做克隆后传递给闭包函数，后续会提供更优的参考写法

**Comment by fantasticsoul** [comment]
https://codesandbox.io/p/sandbox/frosty-dream-lczzvv?file=%2FApp.tsx%3A36%2C28
升级helux到`4.4.0`版本即可，已解决此问题，见[提交](https://github.com/heluxjs/helux/commit/7df95fe26c335031ad3f03d9a1e75e686c36b340)，核心原理是调用`createDraft`时透传了`{ autoRevoke: false }`配置，使用户闭包了子节点的使用场景不报错，但是此节点在结束草稿后只能读取不能修改（修改是无效的）
> 注：limu升级到`3.13.0`后支持了 autoRevoke=false 特性，核心变动见[提交](https://github.com/tnfe/limu/commit/1b87afa10371f787eb2c0e1488647759dcdc4305)
