### ISSUE TITLE
[feat] 文档可以优化， 添加对于原始react技术useState， useContext的推荐替代方案

### ISSUE THREAD

**Issue by 1057105012** [heluxjs/helux#167]
[feat] 文档可以优化， 重点添加对于原始react技术useState， useContext的推荐替代方案， 目前文档对初学者不友好， 容易陷入看起来都很厉害， 但是不知道用哪个的困惑。 这有利于社区纳新

**Comment by fantasticsoul** [comment]
> [feat] 文档可以优化， 重点添加对于原始react技术useState， useContext的推荐替代方案， 目前文档对初学者不友好， 容易陷入看起来都很厉害， 但是不知道用哪个的困惑。 这有利于社区纳新

感谢你的提议，欢迎fork我们的仓库，然后
```bash
pnpm i
cd docs
npm run dev
```
启动好 doc 站点后，就可以修改`docs/docs`目录下各个文件并预留修改后的文档了，然后可以提mr给我们帮助改进文档
